name: Backend Tests

on:
  push:
    branches:
      - feature/github-actions
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Create .env file
      run: |
        echo "DATABASE_URL=sqlite:///app/db/todo.db" >> backend/.env
        echo "SECRET_KEY=f0520f3a5a8834b9ab2dbbc57d5988b8db20db8bfbe8e64fa1abc3e22141e23c" >> backend/.env
        echo "ALGORITHM=HS256" >> backend/.env
        echo "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> backend/.env
        echo "REFRESH_TOKEN_EXPIRE_DAYS=7" >> backend/.env

    - name: Run tests
      run: pytest
