name: Frontend and Backend Tests

on:
  push:
    branches:
      - feature/github-actions
  pull_request:
    branches:
      - master

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "DATABASE_URL=sqlite:///app/db/todo_test.db" >> .env
        echo "SECRET_KEY=f0520f3a5a8834b9ab2dbbc57d5988b8db20db8bfbe8e64fa1abc3e22141e23c" >> .env
        echo "ALGORITHM=HS256" >> .env
        echo "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> .env
        echo "REFRESH_TOKEN_EXPIRE_DAYS=7" >> .env

    - name: Create test SQLite DB file
      run: touch app/db/todo_test.db

    - name: Run tests
      run: pytest 

  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test
