name: Frontend and Backend Tests

on:
  push:
    branches:
      - feature/github-actions
  pull_request:
    branches:
      - master

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Backend Setup and Tests
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: backend/requirements.txt

    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file for backend
      working-directory: backend
      run: |
        echo "DATABASE_URL=sqlite:///./db/todo.db" >> .env
        echo "SECRET_KEY=f0520f3a5a8834b9ab2dbbc57d5988b8db20db8bfbe8e64fa1abc3e22141e23c" >> .env
        echo "ALGORITHM=HS256" >> .env
        echo "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> .env
        echo "REFRESH_TOKEN_EXPIRE_DAYS=7" >> .env

    - name: Create test SQLite DB file
      working-directory: backend
      run:
        mkdir db
        touch db/todo_test.db

    - name: Run tests
      working-directory: backend
      run:
        pytest

    - name: Start backend server for integration tests on frontend
      working-directory: backend
      run:
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
      continue-on-error: false # Without Backend server Frontend Tests will fail

    # Frontend Setup and Tests
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
        channel: stable

    - run: flutter --version
      working-directory: frontend

    - name: Install dependencies
      working-directory: frontend
      run: |
        flutter pub get
        flutter create . --platforms=linux

    - name: Run auth integration test
      uses: gabrielbb/xvfb-action@v1
      with:
        working-directory: frontend
        run:
          flutter test integration_test/auth_integration_test.dart -d linux -r github

    - name: Run tasks integration test
      uses: gabrielbb/xvfb-action@v1
      with:
        working-directory: frontend
        run:
          flutter test integration_test/tasks_integration_test.dart -d linux -r github
